---
title: "gene level analyses for tissue bias"
author: "Haiwang Yang"
date: "7/16/2018"
---

```{r setup, include=FALSE}
library("pheatmap")
library("RColorBrewer")
library("ggplot2")
library(Hmisc)
library(tximportData)
library(tximport)
library(rjson)
library(ggplot2)
library(DESeq2)
```

# basic variables, data, and look-up tables
```{r basic variables, data, and look-up tables}
base_path = "/Users/yangh13/transana/transana/"
dir <- paste0(base_path, "data/")
pwd = paste0(dir,"htseq/FB/")

tissues_in_final_order = c( "wb", "go", "re", "ge", "tx", "dg", "hd", "ac")
sexed_tissues_in_final_order = do.call(paste, expand.grid(c("f","m"), tissues_in_final_order))
tissues_in_final_order_no_ge = c( "wb", "go", "re", "tx", "dg", "hd", "ac")
sexed_tissues_in_final_order_no_ge = do.call(paste, expand.grid(c("f","m"), tissues_in_final_order_no_ge))

samples <- read.table(file.path(dir, paste0(species, ".design")), header = TRUE)
files <- file.path(dir, "salmon", "FB", samples$sample_id, "quant.sf")
names(files) <- samples$sample_id
tx2gene = read.table(paste0(dir, species, ".tx2gene"), header=TRUE)
FBgn2FBtr = read.table(paste0(dir, species, ".FBgn2FBtr"), header=TRUE)
gene2ortho = read.table(paste0(dir, species, ".ortholog"), header=TRUE)
gene2symbol = read.table(paste0(dir, species, ".FBgn2symbol"), header=TRUE)
```


# basic funtions
```{r basic funtions}
first = function(str) {v = strsplit(as.character(str), "\\_")[[1]]; paste(v[1])}
second = function(str) {v = strsplit(as.character(str), "\\_")[[1]]; paste(v[2])}
third = function(str) {v = strsplit(as.character(str), "\\_")[[1]]; paste(v[3])}
fourth = function(str) {v = strsplit(as.character(str), "\\_")[[1]]; paste(v[4])}

get_tissueFull = function(tissue) {gsub("wb", "whole\norganism", gsub("re", "reproductive\ntract", gsub("hd", "head", gsub("dg", "viscera", gsub("tx", "thorax", gsub("ge", "terminalia",gsub("ac", "abdomen", gsub("go","gonad", tissue))))))))}

fetch_files_by_tissue = function(strain, tissue, files){
  return(files[ grepl(paste0(strain, "_"), files) & grepl(paste0("_", tissue, "_"), files)])
}

get_FBgn_for_symbol = function(target_gene){
  target_FBgn = as.character(gene2symbol$FBgn[gene2symbol$symbol == target_gene])
  return(target_FBgn)
}

get_FBtrs_for_symbol = function(target_gene){
  target_FBgn = get_FBgn_for_symbol(target_gene)
  target_FBtrs = as.character(FBgn2FBtr$FBtr[FBgn2FBtr$FBgn == target_FBgn])
  return(target_FBtrs)
}

```



# gene-level salmon-tximport-deseq2 analyses of sex-biased expression
```{r get gene-level salmon-tximport-deseq2 analyses of sex-biased expression}

compare_tissue_and_wb_of_the_same_sex = function(countData_this, colData_this, sex, tissue, alpha=0.05) {
  part_countData0 = countData_this[,names(countData_this)[grepl(paste0(sex, "_wb_"),names(countData_this)) & !grepl("dyak_m_wb_R4",names(countData_this))]]
  part_countData1 = countData_this[,names(countData_this)[grepl(paste0(sex, "_", tissue, "_"),names(countData_this)) & !grepl("dyak_m_wb_R4",names(countData_this))]]
  part_countData = cbind(part_countData0, part_countData1)
  part_colData = colData_this[colnames(part_countData),]
  
  part_colData$tissue = factor(part_colData$tissue, levels = c("wb", tissue))
  
  # do deseq2
  part_dds = DESeqDataSetFromMatrix(part_countData, part_colData, design=~tissue)
  part_dds = estimateSizeFactors(part_dds)
  part_dds = DESeq(part_dds)
  resultsNames(part_dds)
  part_res = results(part_dds)
  summary(part_res,alpha=alpha)
  
  part_dds = estimateSizeFactors(part_dds)
  part_normCounts = counts(part_dds, normalized=TRUE)
  
  part_res_sig = part_res[part_res$padj<alpha & !is.na(part_res$padj),]
  part_res_sig_tt = part_res_sig[part_res_sig$log2FoldChange>0,]
  part_res_sig_wb = part_res_sig[part_res_sig$log2FoldChange<0,]
  FBgns_res_sig_tt = rownames(part_res_sig_tt)
  FBgns_res_sig_wb = rownames(part_res_sig_wb)
  
  FBgns_all = rownames(part_res)
  FBgns_all_minus_m = FBgns_all[! FBgns_all %in% FBgns_res_sig_tt]
  FBgns_unbiased = FBgns_all_minus_m[! FBgns_all_minus_m %in% FBgns_res_sig_wb]
  df_bias_m = data.frame("FBgn_ID"=as.character(unlist(FBgns_res_sig_tt)),"bias"="tt")
  df_bias_unbias = data.frame("FBgn_ID"=FBgns_unbiased,"bias"="unbiased")
  df_bias_f = data.frame("FBgn_ID"=as.character(unlist(FBgns_res_sig_wb)),"bias"="wb")
  df_bias_total = rbind(df_bias_m,df_bias_unbias,df_bias_f)
  df_bias_total$FBgn_ID = as.character(df_bias_total$FBgn_ID)
  df_bias_total = df_bias_total[order(df_bias_total$FBgn_ID),]
  
  
  x = log2(part_normCounts+1)
  x = merge(x, part_res, by="row.names")
  row.names(x) = x$Row.names 
  x = x[,-1]
  
  x$bias = df_bias_total$bias
  
  
  x$col = rgb(0,0,0,0.3)
  x$col[x$bias == "wb"] = rgb(1,0,0,0.6)
  x$col[x$bias == "tt"] = rgb(0,0,1,0.6)
  x$MAplot_mean_R1 = (x[,1] + x[,2])/2
  x$MAplot_log2FoldChange = x$log2FoldChange
  
  return(x)
}


geneana = list()
for (strain in c("w1118", "oreR", species_in_final_order[2:8], "dgriG1")){
  species = strain
  version = "YO"
  tissues = tissues_in_final_order_no_ge[2:7]
  if (strain %in% c("w1118", "oreR")){
    species = "dmel"
    tissues = tissues_in_final_order[2:8]
    version = "FB"
  }
  if (strain %in% c("dgriG1")){
    species = "dgri"
    tissues = tissues_in_final_order[2:8]
  }
  for (tissue in tissues){
    for (sex in c("f", "m")){
      print(paste0(strain, " ", sex, " ", tissue))
      colData_species = read.table(paste0(base_path, "data/", species, ".design"), header=TRUE, sep='',row.names='sample_id')
      countData_species = read.table(paste0(base_path, "data/htseq/", version, "/", species,".htseq_genic.txt.mat"), header=TRUE, sep='\t',row.names="FBgn")
      countData_species = countData_species[!grepl("^ERCC",row.names(countData_species)),]
      countData_species = countData_species[!grepl("^__",row.names(countData_species)),]
      countData_this = countData_species[,grepl(strain, colnames(countData_species))]
      colData_this = colData_species[colnames(countData_this),]
      
      geneana[[paste0(strain, "_", sex, "_", tissue)]] = compare_tissue_and_wb_of_the_same_sex(countData_this, colData_this, sex, tissue, alpha=0.05)
    }
  }
}

strain = "oreR"
for (tissue in tissues_in_final_order){print(table(geneana[[paste0(strain, "_", tissue)]]$bias))}

#save(geneana_tb,file=paste0(base_path, "output/geneana_tb.rtable"))
load(paste0(base_path, "output/geneana_tb.rtable"))

```


```{r barplot summary for gene-level tissuebias-MAplots}
df = data.frame()
for (strain in c("w1118", species_in_final_order[2:8], "dgriG1")){
  species = strain
  tissues = tissues_in_final_order_no_ge
  if (strain %in% c("w1118", "oreR")){
    species = "dmel"
    tissues = tissues_in_final_order
  }
  if (strain %in% c("dgriG1")){
    species = "dgri"
    tissues = tissues_in_final_order
  }
  
  for (tissue in tissues[2:length(tissues)]){
    for (sex in c("f", "m")){
      tb0 = table(geneana_tb[[paste0(strain, "_", sex, "_", tissue)]]$bias)
      cat(strain, " ", sex, " ", tissue," ", tb0,"\n")
      df0 = as.data.frame(tb0)
      colnames(df0) = c("tissuebias", "num")
      df0$species = species
      df0$sex = sex
      df0$tissue = get_tissueFull(tissue)
      df = rbind(df, df0)
    }
  }
}


df = df[,c("species", "sex", "tissue", "tissuebias", "num")]

df$sst = as.character(interaction(df$species, df$sex, df$tissue)) # sst = species sex tissue
df$sst = factor(df$sst, levels = unique(df$sst))

pdf(paste0(base_path, "output/gene.level.tb.bar.summary.pdf"),width=10,height=10,useDingbats=FALSE)
ggplot(df, aes(x = sst, fill= tissuebias, group= tissuebias, y= num)) + geom_bar(stat = "identity") + scale_fill_manual(values = c("green", "grey", "purple")) + theme_bw() + theme(axis.text.x = element_text(angle = 90, hjust = 1)) + ylab("number of genes")
dev.off()

```




```{r correlation of gene-level tissue-bias between w1118 and oreR}
df = data.frame()
for (tissue in tissues[2:length(tissues)]){
  for (sex in c("f", "m")){
    A = table(geneana_tb[[paste0("w1118_", sex, "_", tissue)]]$bias)
    B = table(geneana_tb[[paste0("oreR_", sex, "_", tissue)]]$bias)
    
    df0 = data.frame("w1118" = as.numeric(A["tt"] + A["wb"]), "oreR" = as.numeric(B["tt"] + B["wb"]))
    df = rbind(df, df0)
  }
}

temp = expand.grid(c("f", "m"), tissues[2:length(tissues)])
row.names(df) = paste(temp$Var1, temp$Var2, sep="_")

colMeans(df)
# 8761.429 8582.143 

pdf(paste0(base_path, "output/gene.level.tb.scatterplot.w1118.oreR.pdf"),width=5,height=5,useDingbats=FALSE)
plot(df$w1118, df$oreR, xlab="number of genes with tissue-biased expression in w1118", ylab="number of genes with tissue-biased expression in oreR")
text(8000, 8000, paste0("Pearson's r = ", round(cor(df$w1118, df$oreR), 3)))
dev.off()
```





```{r explore why w1118 and oreR reproductive tract have different tissue bias}

w1118 = geneana_tb$w1118_m_re
table(w1118$bias)
#      tt unbiased       wb 
#    3209     8983     5281 
    
oreR = geneana_tb$oreR_m_re
table(oreR$bias)
#      tt unbiased       wb 
#    3329     6677     7467 

# list of genes showing difference
FBgns_diff = row.names(oreR)[oreR$bias == "wb" & w1118$bias != "wb"]
write.table(FBgns_diff, paste0(base_path, "output/trouble.shooting.w1118.re.txt"),quote=FALSE, row.names=FALSE)

w1118




dmel = cbind(w1118[,1:8],oreR[,1:8])

# show heatmap of 
pdf(paste0(base_path, "output/trouble.shooting.w1118.re.pdf"),width=5,height=5,useDingbats=FALSE)
# scatterplot of logfc
plot(w1118$log2FoldChange, oreR$log2FoldChange)
# heatmap of nrc
pheatmap(as.matrix(dmel[FBgns_diff,]), cluster_rows=FALSE, show_rownames=FALSE, cluster_cols=FALSE, show_colnames = TRUE)
dev.off()

```

```{r specific example for tissue-biased expression}
# top tb gene
w1118 = geneana_tb$w1118_m_go
tail(w1118[order(w1118$padj),])
# pick Gapdh1 FBgn0001091 

for (tissue in tissues[2:length(tissues)]){
  for (sex in c("f", "m")){
    cat(tissue, sex, as.character(geneana_tb[[paste0("w1118_", sex, "_", tissue)]]['FBgn0001091','bias']), "\n")
  }
}

```

